name: Docker

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Polaris-Console Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_version.outputs.VERSION }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.POLARIS_DOCKER_NAME }}
          password: ${{ secrets.POLARIS_DOCKER_PASSWORD }}
          
      - name: Build
        id: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          DOCKER_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          ls -lstrh
          bash build_docker.sh ${DOCKER_TAG}
